flowchart TB

    subgraph ui[UI]
        user[Navegador]
        front[Blade + Livewire \n Tailwind CSS]

        user <--> front
    end

    subgraph app[Laravel App]
        routes[Routes]
        middleware[Middleware]
        controllers[Controllers]
        models[Modelos Eloquent]
        requests[Requests]

        routes <--> middleware
        middleware <--> controllers
        controllers <--> models
        controllers <--> requests
    end

    subgraph datos[Capa de datos / Infra]
        sql[(PostgreSQL)]
        media[Media Library]
        redis[Redis]
        storage[Storage]

        sql <--> media
    end

    front <--> app
    models <--> sql
    models <--> media
    app <--> redis
    app <--> storage

    classDef ui fill:#FFFBEB,stroke:#D97706,stroke-width:1px,color:#111827;
    classDef app fill:#FFE4E6,stroke:#E11D48,stroke-width:1px,color:#111827;
    classDef datos fill:#ECFDF5,stroke:#059669,stroke-width:1px,color:#111827;

    class ui ui;
    class app app;
    class datos datos;